name: Scheduled Flight Script

on:
  schedule:
    # Run at 4:30 AM UTC daily (11:30 PM CST during daylight saving time)
    - cron: "30 4 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python pa-test.py
